// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET104_Project.Models;

namespace NET104_Project.Migrations
{
    [DbContext(typeof(CuahangDbContext))]
    partial class CuahangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NET104_Project.Models.Sanpham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnName("Ten")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnName("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sanpham");
                });

            modelBuilder.Entity("NET104_Project.Models.SanphamChitiet", b =>
                {
                    b.Property<Guid>("IdChitietSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Giaban")
                        .HasColumnType("int");

                    b.Property<int>("Gianhap")
                        .HasColumnType("int");

                    b.Property<Guid>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("IdChitietSp");

                    b.HasIndex("IdSp");

                    b.ToTable("SanphamChitiet");
                });

            modelBuilder.Entity("NET104_Project.Models.SanphamChitiet", b =>
                {
                    b.HasOne("NET104_Project.Models.Sanpham", "Sanpham")
                        .WithMany("SanphamChitiets")
                        .HasForeignKey("IdSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
